title: Lychlov
description: My Personal Blog
author: Lychlov
logo: /static/img/avatar.png
github: https://github.com/lychlov
about: 立志在运营商作码农

baseurl: ""
url: "https://blog.loyowanwan.cc"

allowsearch: true

disqus_shortname: blog-loyowanwan-cc
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000

## default date_format
date_format:
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
gems: [jekyll-paginate, jekyll-gist]
